apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: task-statestore
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: db-secret
        key: connection-string
    - name: tableName
      value: "dapr_state"
    - name: metadataTableName
      value: "dapr_metadata"
auth:
  secretStore: kubernetes
scopes:
  - todo-backend
