apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ .Values.secrets.dbConnectionString | quote }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
